// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using formulaTopTen.Models;

namespace formulaTopTen.Migrations
{
    [DbContext(typeof(ApplikationDbContext))]
    [Migration("20210112190117_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("formulaTopTen.Models.Coment", b =>
                {
                    b.Property<int>("comentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("coment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("driverId")
                        .HasColumnType("int");

                    b.HasKey("comentId");

                    b.HasIndex("driverId");

                    b.ToTable("coment");
                });

            modelBuilder.Entity("formulaTopTen.Models.Driver", b =>
                {
                    b.Property<int>("driverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("driverId");

                    b.ToTable("driver");
                });

            modelBuilder.Entity("formulaTopTen.Models.Coment", b =>
                {
                    b.HasOne("formulaTopTen.Models.Driver", null)
                        .WithMany("coments")
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("formulaTopTen.Models.Driver", b =>
                {
                    b.Navigation("coments");
                });
#pragma warning restore 612, 618
        }
    }
}
